/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#40e0d0',
        'on-primary': '#003733',
        'primary-container': '#76f7e8',
        'on-primary-container': '#00201d',
        'primary-fixed': '#a6fff4',
        'primary-fixed-dim': '#40e0d0',
        secondary: '#4a6360',
        'on-secondary': '#ffffff',
        'secondary-container': '#cce8e4',
        'on-secondary-container': '#072e2b',
        tertiary: '#4a607c',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#d3e3ff',
        'on-tertiary-container': '#041c35',
        'tertiary-fixed': '#d3e3ff',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        background: '#f8fdff',
        'on-background': '#191c1d',
        surface: '#f8fdff',
        'on-surface': '#191c1d',
        'on-surface-variant': '#3f4947',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eff5f4',
        'surface-container': '#e9efee',
        'surface-container-high': '#e3e9e9',
        'surface-container-highest': '#dee3e3',
        'surface-variant': '#dae5e3',
        outline: '#6f7977',
        'outline-variant': '#bec9c7',
      },
      fontFamily: {
        serif: ['"Noto Serif"', 'serif'],
        sans: ['Lexend', 'sans-serif'],
      },
      spacing: {
        xs: '4px',
        sm: '12px',
        base: '8px',
        md: '24px',
        lg: '40px',
        xl: '64px',
        gutter: '16px',
        'container-margin': '20px',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
      },
      boxShadow: {
        glass: '0 8px 32px 0 rgba(30, 27, 36, 0.08)',
        'glow-primary': '0 4px 12px rgba(64, 224, 208, 0.3)',
      },
    },
  },
  plugins: [],
}
